import type { InputMarketParams } from '@morpho-org/blue-sdk'
import type { Address, Client, Hex, Transport } from 'viem'

import {
  type BatchLensTransportType,
  MAX_INITCODE_SIZE,
  readDeploylessBatchLens
} from '@repo/utils'
import { sol } from 'soltag'

// Single-file soltag lens: reads everything a reallocation pass needs for a batch of vaults inside
// ONE eth_call against one pinned block — the vault's roles, its withdraw queue, and per market the
// params, accrued Blue state, the vault's position, its cap, and the IRM's rateAtTarget. It replaces
// `fetchAccrualVault`'s per-market fan-out (~55–65 billed JSON-RPC calls for a 10-market vault) with
// a single billed call, and it removes the client-side accrual entirely: `Morpho.accrueInterest` runs
// inside the simulation, so every read below is exactly what the market holds at that block.
//
// The `lens` entrypoint is therefore state-changing (`accrueInterest` is `nonpayable`). Nothing
// escapes the `eth_call` — the simulation's writes are discarded — but see `readVaultV1Lens` for why
// that costs one deliberate ABI relabel on the read path.
//
// The soltag type codegen (`.soltag/types.d.ts`, regenerated by the `soltag` CLI before typecheck)
// narrows the compiled `.abi`, so viem encodes the inputs and decodes the structs natively; no
// hand-written ABI fragment and no manual abi.encode/decode. Compiled to a deployless factory by
// soltag's Vitest/esbuild integrations; `sol``` throws if the transform is not active.
export const VaultV1ReallocationLens = sol('VaultV1ReallocationLens')`
// SPDX-License-Identifier: GPL-2.0-or-later
pragma solidity ^0.8.19;

struct MarketParams { address loanToken; address collateralToken; address oracle; address irm; uint256 lltv; }
struct Market {
  uint128 totalSupplyAssets;
  uint128 totalSupplyShares;
  uint128 totalBorrowAssets;
  uint128 totalBorrowShares;
  uint128 lastUpdate;
  uint128 fee;
}
struct Position { uint256 supplyShares; uint128 borrowShares; uint128 collateral; }

interface IMorpho {
  function market(bytes32 id) external view returns (Market memory);
  function position(bytes32 id, address user) external view returns (Position memory);
  function idToMarketParams(bytes32 id) external view returns (MarketParams memory);
  function accrueInterest(MarketParams memory marketParams) external;
}

interface IMetaMorpho {
  function owner() external view returns (address);
  function curator() external view returns (address);
  function isAllocator(address target) external view returns (bool);
  function withdrawQueueLength() external view returns (uint256);
  function withdrawQueue(uint256 index) external view returns (bytes32);
  function config(bytes32 id) external view returns (uint184 cap, bool enabled, uint64 removableAt);
}

interface IAdaptiveCurveIrm { function rateAtTarget(bytes32 id) external view returns (int256); }

contract VaultV1ReallocationLens {
  uint256 internal constant VIRTUAL_SHARES = 1e6;
  uint256 internal constant VIRTUAL_ASSETS = 1;

  IMorpho public immutable MORPHO;
  address public immutable ADAPTIVE_CURVE_IRM;

  // One vault, plus the EOA whose allocator role is being probed. Role data rides the same call as
  // the market snapshot, so the tick needs no separate isAllocator read.
  struct Input { address vault; address eoa; }

  struct MarketOut {
    bytes32 id;
    MarketParams params;
    uint256 totalSupplyAssets;   // post-accrual
    uint256 totalBorrowAssets;   // post-accrual
    uint256 cap;                 // the vault's config(id).cap
    uint256 vaultAssets;         // the vault's supplyShares converted down, post-accrual
    uint256 rateAtTarget;        // 0 unless irm is the chain's canonical AdaptiveCurveIRM
  }

  struct VaultOut {
    address owner;
    address curator;
    bool isAllocator;
    MarketOut[] markets;         // withdraw-queue order
  }

  constructor(IMorpho morpho, address adaptiveCurveIrm) {
    MORPHO = morpho;
    ADAPTIVE_CURVE_IRM = adaptiveCurveIrm;
  }

  // SharesMathLib.toAssetsDown: the vault's own position, rounded against the vault.
  function _toAssetsDown(uint256 shares, uint256 totalAssets, uint256 totalShares) internal pure returns (uint256) {
    return (shares * (totalAssets + VIRTUAL_ASSETS)) / (totalShares + VIRTUAL_SHARES);
  }

  // No per-element try/catch, unlike the liquidation lenses: the fetcher submits one vault per call,
  // so a revert IS that vault's failure and the real reason should reach the tick's vault.error log
  // rather than being flattened into a valid=false row.
  function lens(Input[] calldata input) external returns (VaultOut[] memory output) {
    output = new VaultOut[](input.length);
    for (uint256 i = 0; i < input.length; i++) output[i] = _readVault(input[i]);
  }

  function _readVault(Input calldata e) internal returns (VaultOut memory o) {
    IMetaMorpho vault = IMetaMorpho(e.vault);
    o.owner = vault.owner();
    o.curator = vault.curator();
    o.isAllocator = vault.isAllocator(e.eoa);

    uint256 length = vault.withdrawQueueLength();
    o.markets = new MarketOut[](length);
    for (uint256 i = 0; i < length; i++) {
      bytes32 id = vault.withdrawQueue(i);
      MarketParams memory params = MORPHO.idToMarketParams(id);
      // Accrue FIRST. Every read after this line — the market totals, the vault's assets, and the
      // IRM's STORED rateAtTarget, which only advances when Blue calls borrowRate — is then the
      // exact on-chain state at this block, with no client-side accrual to keep in sync.
      MORPHO.accrueInterest(params);
      Market memory m = MORPHO.market(id);
      Position memory p = MORPHO.position(id, e.vault);
      (uint184 cap,,) = vault.config(id);

      uint256 rate = 0;
      if (params.irm == ADAPTIVE_CURVE_IRM) {
        int256 signedRate = IAdaptiveCurveIrm(params.irm).rateAtTarget(id);
        if (signedRate > 0) rate = uint256(signedRate);
      }

      o.markets[i] = MarketOut({
        id: id,
        params: params,
        totalSupplyAssets: m.totalSupplyAssets,
        totalBorrowAssets: m.totalBorrowAssets,
        cap: cap,
        vaultAssets: _toAssetsDown(p.supplyShares, m.totalSupplyAssets, m.totalSupplyShares),
        rateAtTarget: rate
      });
    }
  }
}
`

/** One vault to read, plus the EOA whose `isAllocator` bit is wanted alongside its snapshot. */
type LensInput = { vault: Address; eoa: Address }

/** The decoded Solidity `MarketOut` struct (uint* → bigint per viem). */
type LensMarketOut = {
  id: Hex
  params: InputMarketParams
  totalSupplyAssets: bigint
  totalBorrowAssets: bigint
  cap: bigint
  vaultAssets: bigint
  rateAtTarget: bigint
}

/** The decoded Solidity `VaultOut` struct. */
type LensVaultOut = {
  owner: Address
  curator: Address
  isAllocator: boolean
  markets: readonly LensMarketOut[]
}

// `accrueInterest` makes the entrypoint `nonpayable`, and viem's `readContract` (which
// `readDeploylessBatchLens` builds on) only accepts `view`/`pure` functions. `stateMutability` is
// part of neither the selector nor the encoding — https://docs.soliditylang.org/en/latest/abi-spec.html
// — and `eth_call` executes the writes in a state it then throws away, so relabelling this one item
// `view` for the read path is a pure typing concern. Everything else stays generated: the struct
// codecs, and therefore the decode, are the soltag ABI's.
type ViewItem<item> = {
  readonly [key in keyof item]: key extends 'stateMutability' ? 'view' : item[key]
}

type AsViewAbi<abi extends readonly unknown[]> = {
  readonly [index in keyof abi]: abi[index] extends { readonly name: 'lens' }
    ? ViewItem<abi[index]>
    : abi[index]
}

const asViewAbi = <abi extends readonly unknown[]>(abi: abi): AsViewAbi<abi> =>
  abi.map(item =>
    typeof item === 'object' && item !== null && 'name' in item && item.name === 'lens'
      ? { ...item, stateMutability: 'view' }
      : item
  ) as unknown as AsViewAbi<abi>

/**
 * Reads the reallocation lens for every vault in one deployless `eth_call`, pinned to `blockNumber`
 * so the whole snapshot is coherent across markets and reproducible. Returns a map keyed by the
 * lower-cased vault address.
 *
 * Throws whatever the lens reverted with — the caller (one vault per call, see `fetchVaultData`)
 * treats that as that vault's failure. The `client` must use viem-dlc's deployless transport (built
 * by bot-kit's `createDeploylessClient`).
 */
export const readVaultV1Lens = async (
  client: Client<Transport<BatchLensTransportType>>,
  addresses: { morpho: Address; adaptiveCurveIrm: Address },
  vaults: readonly LensInput[],
  blockNumber: bigint
): Promise<Map<string, LensVaultOut>> => {
  const compiled = VaultV1ReallocationLens.with(addresses.morpho, addresses.adaptiveCurveIrm)
  return readDeploylessBatchLens(
    client,
    {
      ...compiled,
      abi: asViewAbi(compiled.abi),
      functionName: 'lens',
      args: [vaults],
      blockNumber,
      batch: {
        batchSize: MAX_INITCODE_SIZE,
        exfil: 'revert',
        compress: false,
        // A vault is a coarse batch element: it fans out 6 sub-calls per market (params, accrual,
        // market, position, config, rateAtTarget) over a queue that MetaMorpho caps at 30, and
        // `accrueInterest` is the expensive one (IRM borrowRate + storage writes). `linear` budgets a
        // full 30-market queue; `constant` folds in the deployless CREATE + code-deposit overhead.
        // Under-budgeting is self-correcting — viem-dlc's chunker halve-and-retries any batch over
        // the RPC gas cap — and the production fetcher submits one vault per call anyway.
        gas: { default: { constant: 1_500_000, linear: 6_000_000, quadratic: 0 } }
      }
    },
    ({ vault }) => vault.toLowerCase(),
    (_input, out): LensVaultOut => out
  )
}
