import type { Address, Client, Hex, Transport } from 'viem'

import { sol } from 'soltag'

import type { Market } from '../execution/encode-call'
import type { BatchLensTransportType } from './read-deployless-batch-lens'

import { MAX_INITCODE_SIZE, readDeploylessBatchLens } from './read-deployless-batch-lens'

// Single-file soltag lens: reads everything the liquidation decision depends on for a batch of
// (id, borrower) pairs inside one eth_call against a single block.timestamp. Takes an `Input[]` and
// returns a `LensOut[]` — the soltag type codegen (`.soltag/types.d.ts`, regenerated by the `soltag`
// CLI before typecheck) narrows the compiled `.abi`, so viem encodes the inputs and decodes the
// structs natively; no hand-written ABI fragment or manual abi.encode/decode is needed. Reads the
// full Market on-chain via Midnight.toMarket(id) — the id is a cryptographic commitment to the
// struct, so no off-chain market input or `id == toId(market)` re-check is needed — then composes
// liquidatability + the sizing inputs (maxDebt/badDebt/best-collateral) the way liquidate() does and
// returns the Market so the caller can encode the liquidate call. Compiled to a deployless factory by
// the soltag bun preload (see ../../soltag.preload.ts); `sol``` throws if not active.
export const MidnightLiquidationLens = sol('MidnightLiquidationLens')`
// SPDX-License-Identifier: GPL-2.0-or-later
pragma solidity ^0.8.19;

struct CollateralParams { address token; uint256 lltv; uint256 liquidationCursor; address oracle; }
struct Market {
  uint256 chainId;
  address midnight;
  address loanToken;
  CollateralParams[] collateralParams;
  uint256 maturity;
  uint256 rcfThreshold;
  address enterGate;
  address liquidatorGate;
}

interface IMidnight {
  function toMarket(bytes32 id) external view returns (Market memory);
  function liquidationLocked(bytes32 id, address user) external view returns (bool);
  function debt(bytes32 id, address user) external view returns (uint128);
  function collateralBitmap(bytes32 id, address user) external view returns (uint128);
  function collateral(bytes32 id, address user, uint256 index) external view returns (uint128);
}
interface IOracle { function price() external view returns (uint256); }
interface ILiquidatorGate { function canLiquidate(address account) external view returns (bool); }

contract MidnightLiquidationLens {
  uint256 internal constant WAD = 1e18;
  uint256 internal constant ORACLE_PRICE_SCALE = 1e36;

  IMidnight public immutable MIDNIGHT;

  // One (id, borrower) pair. caller is the Executor (the liquidate msg.sender), whose
  // canLiquidate is checked -- not the EOA.
  struct Input { bytes32 id; address borrower; address caller; }

  struct LensOut {
    bool valid; bool hasDebt; bool healthy; bool locked; bool gateAllows;
    uint64 blockTimestamp;
    uint128 debt; uint128 maxDebt; uint128 badDebt; uint128 activatedBitmap;
    uint8 bestCollateralIdx; uint128 bestCollateralAmt;
    uint256 bestCollateralPrice; uint256 bestCollateralMaxLif; uint256 bestCollateralLltv;
    Market market;
  }

  constructor(IMidnight midnight) { MIDNIGHT = midnight; }

  function _mulDivDown(uint256 x, uint256 y, uint256 d) internal pure returns (uint256) { return (x * y) / d; }
  function _mulDivUp(uint256 x, uint256 y, uint256 d) internal pure returns (uint256) { return (x * y + (d - 1)) / d; }
  // Derives maxLif from (lltv, liquidationCursor), mirroring ConstantsLib.maxLif @ 336b924a exactly
  // (mulDivDown on both divisions): maxLif = WAD / (WAD - cursor*(WAD-lltv)/WAD). The on-chain
  // Market now stores liquidationCursor instead of the pre-derived maxLif (no backticks here: they
  // would terminate the sol tagged-template).
  function _maxLif(uint256 lltv, uint256 liquidationCursor) internal pure returns (uint256) {
    return _mulDivDown(WAD, WAD, WAD - _mulDivDown(liquidationCursor, WAD - lltv, WAD));
  }
  function _zeroFloorSub(uint256 x, uint256 y) internal pure returns (uint256) { return x > y ? x - y : 0; }
  function _msb(uint128 bitmap) internal pure returns (uint256 res) { while (bitmap >> (res + 1) != 0) { res++; } }
  function _clearBit(uint128 bitmap, uint256 bit) internal pure returns (uint128) { return uint128(bitmap & ~(uint128(1) << bit)); }

  function lens(Input[] calldata input) external view returns (LensOut[] memory output) {
    output = new LensOut[](input.length);
    for (uint256 i = 0; i < input.length; i++) {
      // Per-element isolation: a revert (bad oracle, unknown id) leaves output[i] as a zeroed
      // LensOut (valid=false) instead of reverting the whole batch. computeOne is external view, so
      // the self-call is a STATICCALL and cannot mutate state.
      try this.computeOne(input[i]) returns (LensOut memory o) {
        output[i] = o;
      } catch {
        // output[i] keeps its zeroed (valid=false) default.
      }
    }
  }

  function computeOne(Input calldata e) external view returns (LensOut memory o) {
    // Reverts MarketNotCreated for an unknown id — caught by lens()'s per-element try/catch, which
    // leaves a zeroed (valid=false) row. A successful read is the canonical Market for this id.
    Market memory market = MIDNIGHT.toMarket(e.id);

    o.blockTimestamp = uint64(block.timestamp);
    o.valid = true;
    o.market = market;

    uint256 debt = uint256(MIDNIGHT.debt(e.id, e.borrower));
    o.debt = uint128(debt);
    o.hasDebt = debt > 0;
    o.locked = MIDNIGHT.liquidationLocked(e.id, e.borrower);

    address gate = market.liquidatorGate;
    if (gate == address(0)) {
      o.gateAllows = true;
    } else {
      try ILiquidatorGate(gate).canLiquidate(e.caller) returns (bool ok) { o.gateAllows = ok; }
      catch { o.gateAllows = false; }
    }

    o.activatedBitmap = MIDNIGHT.collateralBitmap(e.id, e.borrower);
    _accumulate(o, market, e.id, e.borrower, debt);
    _selectBest(o, market, e.id, e.borrower);
  }

  // Two passes (not one combined loop): a single loop carrying maxDebt/badDebt/argmax exceeds the
  // EVM stack ("stack too deep"). Each slot is re-read in _selectBest — acceptable for a read-only
  // lens. _accumulate mirrors the liquidate() loop exactly (maxDebt down-down; badDebt ceil-ceil,
  // seeded with debt and floored at 0 per slot).
  function _accumulate(LensOut memory o, Market memory market, bytes32 id, address borrower, uint256 debt) private view {
    uint256 maxDebt;
    uint256 badDebt = debt;
    uint128 work = o.activatedBitmap;
    while (work != 0) {
      uint256 idx = _msb(work);
      CollateralParams memory cp = market.collateralParams[idx];
      uint256 amt = uint256(MIDNIGHT.collateral(id, borrower, idx));
      uint256 price = IOracle(cp.oracle).price();
      maxDebt += _mulDivDown(_mulDivDown(amt, price, ORACLE_PRICE_SCALE), cp.lltv, WAD);
      badDebt = _zeroFloorSub(badDebt, _mulDivUp(_mulDivUp(amt, price, ORACLE_PRICE_SCALE), WAD, _maxLif(cp.lltv, cp.liquidationCursor)));
      work = _clearBit(work, idx);
    }
    o.maxDebt = uint128(maxDebt);
    o.badDebt = uint128(badDebt);
    o.healthy = maxDebt >= debt; // matches isHealthy's final return
  }

  // Picks the activated slot with the greatest USD value (collateral*price/SCALE).
  function _selectBest(LensOut memory o, Market memory market, bytes32 id, address borrower) private view {
    uint256 bestValue;
    bool haveBest;
    uint128 work = o.activatedBitmap;
    while (work != 0) {
      uint256 idx = _msb(work);
      CollateralParams memory cp = market.collateralParams[idx];
      uint256 amt = uint256(MIDNIGHT.collateral(id, borrower, idx));
      uint256 price = IOracle(cp.oracle).price();
      uint256 value = _mulDivDown(amt, price, ORACLE_PRICE_SCALE);
      if (!haveBest || value > bestValue) {
        haveBest = true;
        bestValue = value;
        o.bestCollateralIdx = uint8(idx);
        o.bestCollateralAmt = uint128(amt);
        o.bestCollateralPrice = price;
        o.bestCollateralMaxLif = _maxLif(cp.lltv, cp.liquidationCursor);
        o.bestCollateralLltv = cp.lltv;
      }
      work = _clearBit(work, idx);
    }
  }
}
`

/** What the lens reads for one (id, borrower) pair. The lens fetches the Market on-chain from
 * `id`; `caller` is the Executor (the liquidate `msg.sender`), whose `canLiquidate` is checked —
 * not the EOA. */
export type LensInput = { id: Hex; borrower: Address; caller: Address }

/** Decoded `LensOut` (uint8 → number, uint64/128/256 → bigint, per viem). */
export type LensOut = {
  valid: boolean
  hasDebt: boolean
  healthy: boolean
  locked: boolean
  gateAllows: boolean
  blockTimestamp: bigint
  debt: bigint
  maxDebt: bigint
  badDebt: bigint
  activatedBitmap: bigint
  bestCollateralIdx: number
  bestCollateralAmt: bigint
  bestCollateralPrice: bigint
  bestCollateralMaxLif: bigint
  bestCollateralLltv: bigint
  /** Full Market read on-chain via `toMarket(id)`; pass straight into `liquidate`. */
  market: Market
}

/** Stable per-pair key for the result map. */
export function lensKey(id: Hex, borrower: Address): string {
  return `${id.toLowerCase()}:${borrower.toLowerCase()}`
}

/**
 * Reads the liquidation lens for every pair in one deployless, chunked `eth_call` (no signer, no
 * cache — decisions need fresh state). The lens fetches each Market on-chain from its `id`. Returns
 * a map keyed by {@link lensKey}. The `client` must use viem-dlc's deployless transport (built in
 * `client.ts`).
 */
export async function readMidnightLiquidationLens(
  client: Client<Transport<BatchLensTransportType>>,
  midnight: Address,
  pairs: readonly LensInput[]
): Promise<Map<string, LensOut>> {
  return readDeploylessBatchLens(
    client,
    {
      ...MidnightLiquidationLens.with(midnight),
      functionName: 'lens',
      args: [pairs],
      batch: {
        batchSize: MAX_INITCODE_SIZE,
        exfil: 'revert',
        compress: false,
        gas: { default: { constant: 1_300_000, linear: 55_000, quadratic: 0 } }
      }
    },
    ({ id, borrower }) => lensKey(id, borrower),
    (_input, out): LensOut => out
  )
}
