#!/usr/bin/env node
/**
 * Generates the soltag entrypoints under `src/` from the `.sol` files in `solidity/`:
 *
 *   solidity/interfaces/IFoo.sol  ->  src/abis.ts     `export const FooAbi = sol('IFoo')`...`.abi`
 *   solidity/Bar.sol              ->  src/contracts.ts `export const Bar  = sol('Bar')`...``
 *
 * Interfaces export only `.abi` (they have no bytecode). Top-level contracts export the WHOLE
 * soltag object (abi + bytecode + deployless factory), since a caller may want more than the ABI.
 *
 * Run via `bun run --filter @repo/contracts generate` after adding/renaming/removing a `.sol` file.
 * The output is checked in — we don't run codegen on every build.
 */
import { readdirSync, writeFileSync } from 'node:fs'
import { dirname, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'

const __dirname = dirname(fileURLToPath(import.meta.url))
const ROOT = resolve(__dirname, '..')
const SOLIDITY_DIR = resolve(ROOT, 'solidity')
const INTERFACES_DIR = resolve(SOLIDITY_DIR, 'interfaces')

/** Renders a generated `src/*.ts` module (header + soltag import + body). */
function render(sourceGlob, body) {
  return `// AUTO-GENERATED by scripts/generate-abis.mjs from solidity/${sourceGlob}.
// Run \`bun run --filter @repo/contracts generate\` after adding, renaming, or removing a .sol file.
// Do not edit by hand — your changes will be overwritten.

import { sol, solFile } from 'soltag'

${body}
`
}

// Interfaces (solidity/interfaces/IFoo.sol) -> src/abis.ts: `IFoo` -> `FooAbi`, exporting `.abi`.
const interfaceFiles = readdirSync(INTERFACES_DIR)
  .filter(f => f.endsWith('.sol'))
  .sort()

const abisBody = interfaceFiles
  .map(file => {
    const iface = file.slice(0, -4) // drop ".sol"
    if (!iface.startsWith('I')) {
      throw new Error(`[generate-abis] ${file}: interface filenames must start with "I".`)
    }
    const exportName = `${iface.slice(1)}Abi` // `IMidnight` -> `MidnightAbi`
    return `export const ${exportName} = sol('${iface}')\`
  \${solFile('../solidity/interfaces/${file}', { raw: true })}
\`.abi`
  })
  .join('\n\n')

writeFileSync(resolve(ROOT, 'src/abis.ts'), render('interfaces/*.sol', abisBody))

// Top-level contracts (solidity/Bar.sol) -> src/contracts.ts: `Bar` -> `Bar`, exporting the whole
// soltag object (abi + bytecode + factory).
const contractFiles = readdirSync(SOLIDITY_DIR, { withFileTypes: true })
  .filter(entry => entry.isFile() && entry.name.endsWith('.sol'))
  .map(entry => entry.name)
  .sort()

const contractsBody = contractFiles
  .map(file => {
    const name = file.slice(0, -4) // drop ".sol"; `Executor.sol` -> `Executor`
    return `export const ${name} = sol('${name}')\`
  \${solFile('../solidity/${file}', { raw: true })}
\``
  })
  .join('\n\n')

writeFileSync(resolve(ROOT, 'src/contracts.ts'), render('*.sol', contractsBody))

console.log(
  `[generate-abis] wrote src/abis.ts (${interfaceFiles.length} interfaces), ` +
    `src/contracts.ts (${contractFiles.length} contracts)`
)
