// AUTO-GENERATED by scripts/codegen.ts from solidity/interfaces/*.sol.
// Run `pnpm --filter @repo/contracts run generate` after adding, renaming, or removing a .sol file.
// Do not edit by hand — your changes will be overwritten.

import { sol, solFile } from 'soltag'

export const MidnightAbi = sol('IMidnight')`
  ${solFile('../solidity/interfaces/IMidnight.sol', { raw: true })}
`.abi

export const MorphoAbi = sol('IMorpho')`
  ${solFile('../solidity/interfaces/IMorpho.sol', { raw: true })}
`.abi
