// AUTO-GENERATED by scripts/codegen.ts from solidity/*.sol.
// Run `pnpm --filter @repo/contracts run generate` after adding, renaming, or removing a .sol file.
// Do not edit by hand — your changes will be overwritten.

import { sol, solFile } from 'soltag'

export const Executor = sol('Executor')`
  ${solFile('../solidity/Executor.sol', { raw: true })}
`
