// AUTO-GENERATED by scripts/codegen.ts from solidity/*.sol.
// Run `bun run --filter @repo/contracts generate` after adding, renaming, or removing a .sol file.
// Do not edit by hand — your changes will be overwritten.

import { sol, solFile } from 'soltag'

export const CrossedBooksResolver = sol('CrossedBooksResolver')`
  ${solFile('../solidity/CrossedBooksResolver.sol', { raw: true })}
`

export const Executor = sol('Executor')`
  ${solFile('../solidity/Executor.sol', { raw: true })}
`

export const RevokeOffers = sol('RevokeOffers')`
  ${solFile('../solidity/RevokeOffers.sol', { raw: true })}
`
