#!/usr/bin/env bun
import openapiTS, { astToString } from 'openapi-typescript'
import prompts from 'prompts'

// Manual-only spec sync (never wire into CI / prebuild — the build must stay offline so a flaky
// upstream can't break it, and schema updates land as reviewable diffs). Port of
// `apps/markets-v2-app/scripts/pull-schemas.ts` (prime-monorepo) to bun.
//
// The Midnight API serves its reference UI (Scalar) with the OpenAPI document inlined as the
// `content` field of `Scalar.createApiReference('#app', { ..., "content": { <spec> } })` rather
// than at a standalone JSON endpoint, so we fetch the docs page and brace-match the `content`
// object out of it. Run with `--yes` (or any non-TTY shell) to skip the confirmation prompt.

const DEFAULT_DOCS_URL = 'https://api.morpho.dev/midnight/docs'

function extractInlinedSpec(html: string): unknown {
  const key = html.indexOf('"content"')
  if (key === -1) throw new Error('docs page has no inlined "content" OpenAPI spec')
  const start = html.indexOf('{', key)
  let depth = 0
  let inString = false
  let escaped = false
  for (let i = start; i < html.length; i++) {
    const char = html[i]
    if (inString) {
      if (escaped) escaped = false
      else if (char === '\\') escaped = true
      else if (char === '"') inString = false
      continue
    }
    if (char === '"') inString = true
    else if (char === '{') depth++
    else if (char === '}') {
      depth--
      if (depth === 0) return JSON.parse(html.slice(start, i + 1))
    }
  }
  throw new Error('unbalanced braces while extracting the inlined spec')
}

const docsUrl = process.env.MIDNIGHT_DOCS_URL ?? DEFAULT_DOCS_URL
const packageRoot = new URL('../', import.meta.url)
// Output lives under `generated/` so the repo's existing oxlint/oxfmt `**/generated` ignores
// (and the knip ignore added alongside this script) cover both the spec and the emitted types.
const openapiPath = new URL('src/api/generated/openapi.json', packageRoot)
const generatedPath = new URL('src/api/generated/index.ts', packageRoot)
const skipPrompt = process.argv.includes('--yes') || !process.stdin.isTTY

if (!skipPrompt) {
  const { confirmed } = await prompts({
    type: 'confirm',
    name: 'confirmed',
    message: `Pull the OpenAPI spec from ${docsUrl} and regenerate src/api/{openapi.json,generated.ts}?`,
    initial: true
  })
  if (!confirmed) {
    console.log('Aborted.')
    process.exit(0)
  }
}

console.log(`Fetching ${docsUrl} ...`)
const response = await fetch(docsUrl, {
  headers: { 'User-Agent': 'midnight-liquidation/pull-schemas' }
})
if (!response.ok) throw new Error(`docs fetch failed: HTTP ${response.status}`)

const spec = extractInlinedSpec(await response.text())
await Bun.write(openapiPath, `${JSON.stringify(spec, null, 2)}\n`)
console.log(`Wrote ${openapiPath.pathname}`)

const ast = await openapiTS(spec as Parameters<typeof openapiTS>[0])
const header =
  '// AUTO-GENERATED by `bun pull-schemas` from the Midnight API OpenAPI spec.\n' +
  '// Do not edit by hand; re-run the script to refresh. Source of truth: src/api/openapi.json\n\n'
await Bun.write(generatedPath, header + astToString(ast))
console.log(`Wrote ${generatedPath.pathname}`)
