import type { Client, Transport } from 'viem'

import { type BatchLensTransportType, lensKey, readDeploylessBatchLens } from '@repo/utils'
import { sol } from 'soltag'
import { type Address } from 'viem'

import type { MarketParams } from '../market'

import { marketId } from '../market'

// Single-file soltag lens: reads everything the liquidation decision depends on for a batch of
// (marketParams, borrower) pairs inside one eth_call against a single block.timestamp. Takes an
// `Input[]` and returns a `LensOut[]` — the soltag type codegen (`.soltag/types.d.ts`, regenerated by
// the `soltag` CLI before typecheck) narrows the compiled `.abi`, so viem encodes the inputs and
// decodes the structs natively; no hand-written ABI fragment or manual abi.encode/decode is needed.
//
// Blue debt accrues continuously, so the lens simulates interest accrual before the health check.
// MarketParams are recovered onchain via idToMarketParams(id) (see ./market-params.ts); the lens
// re-derives the id from the supplied params onchain, so mismatched params read an uncreated market
// and return valid=false.
//
// Compiled to a deployless factory by soltag's Vitest/esbuild integrations; `sol``` throws if the
// transform is not active.
export const BlueLiquidationLens = sol('BlueLiquidationLens')`
// SPDX-License-Identifier: GPL-2.0-or-later
pragma solidity ^0.8.19;

struct MarketParams { address loanToken; address collateralToken; address oracle; address irm; uint256 lltv; }
struct Market {
  uint128 totalSupplyAssets;
  uint128 totalSupplyShares;
  uint128 totalBorrowAssets;
  uint128 totalBorrowShares;
  uint128 lastUpdate;
  uint128 fee;
}
struct Position { uint256 supplyShares; uint128 borrowShares; uint128 collateral; }

interface IMorpho {
  function market(bytes32 id) external view returns (Market memory);
  function position(bytes32 id, address user) external view returns (Position memory);
}
interface IIrm {
  function borrowRateView(MarketParams memory marketParams, Market memory market) external view returns (uint256);
}
interface IOracle { function price() external view returns (uint256); }

contract BlueLiquidationLens {
  uint256 internal constant WAD = 1e18;
  uint256 internal constant ORACLE_PRICE_SCALE = 1e36;
  uint256 internal constant VIRTUAL_SHARES = 1e6;
  uint256 internal constant VIRTUAL_ASSETS = 1;

  IMorpho public immutable MORPHO;

  // One (marketParams, borrower) pair. The lens derives the id from params on-chain, so a caller
  // cannot smuggle in mismatched params — everything downstream keys off the committed id.
  struct Input { MarketParams params; address borrower; }

  struct LensOut {
    bool valid;                     // id derived + market exists
    bool hasDebt;                   // borrowShares > 0
    bool healthy;                   // maxBorrow >= borrowed  (== the contract's _isHealthy)
    uint64 blockTimestamp;          // avoid host-clock drift; LIF/sizing evaluate against this
    uint128 borrowShares;
    uint128 collateral;
    uint256 accruedTotalBorrowAssets;
    uint256 totalBorrowShares;      // accrual never changes totalBorrowShares, so this is the raw read
    uint256 collateralPrice;        // raw oracle price (ORACLE_PRICE_SCALE units)
    uint256 lltv;
  }

  constructor(IMorpho morpho) { MORPHO = morpho; }

  function _mulDivDown(uint256 x, uint256 y, uint256 d) internal pure returns (uint256) { return (x * y) / d; }
  function _mulDivUp(uint256 x, uint256 y, uint256 d) internal pure returns (uint256) { return (x * y + (d - 1)) / d; }
  function _wMulDown(uint256 x, uint256 y) internal pure returns (uint256) { return _mulDivDown(x, y, WAD); }

  // First three non-zero terms of e^(nx) - 1 (MathLib.wTaylorCompounded); each term floors independently.
  function _wTaylorCompounded(uint256 x, uint256 n) internal pure returns (uint256) {
    uint256 firstTerm = x * n;
    uint256 secondTerm = _mulDivDown(firstTerm, firstTerm, 2 * WAD);
    uint256 thirdTerm = _mulDivDown(secondTerm, firstTerm, 3 * WAD);
    return firstTerm + secondTerm + thirdTerm;
  }

  // SharesMathLib.toAssetsUp: shares -> assets, rounding up (matches _isHealthy's 'borrowed').
  function _toAssetsUp(uint256 shares, uint256 totalAssets, uint256 totalShares) internal pure returns (uint256) {
    return _mulDivUp(shares, totalAssets + VIRTUAL_ASSETS, totalShares + VIRTUAL_SHARES);
  }

  // Must not revert for an input it simply cannot price: a declined element is indistinguishable
  // from one the provider refused, so an unpriceable input is data (valid=false) and a revert is
  // left to mean something is wrong.
  //
  // Running out of gas is NOT such an input. EIP-150 keeps 1/64 of the forwarded gas in this frame,
  // so a child that died of gas still lets the catch run and would be recorded as a SERVED
  // valid=false row — which the envelope never retries and declined:'throw' cannot see, silently
  // dropping the position from the liquidation set. Returndata cannot tell the two apart, but gas
  // can: a child that consumed essentially its whole allowance ran out, so re-revert and let the
  // element be declined (loud) rather than answered wrongly (silent).
  function computeOne(Input calldata e) external view returns (LensOut memory o) {
    uint256 forwarded = gasleft();
    try this.computeOneInner(e) returns (LensOut memory r) {
      o = r;
    } catch {
      if (gasleft() < forwarded / 32) revert();
      // o keeps its zeroed (valid=false) default.
    }
  }

  function computeOneInner(Input calldata e) external view returns (LensOut memory o) {
    // id-commitment check: derive the id from the SUPPLIED params and read state at it. A forged
    // param set derives an id with no market (lastUpdate == 0) -> revert -> valid=false.
    bytes32 id = keccak256(abi.encode(e.params));
    Market memory m = MORPHO.market(id);
    require(m.lastUpdate != 0, "market not created");
    Position memory p = MORPHO.position(id, e.borrower);

    o.blockTimestamp = uint64(block.timestamp);
    o.valid = true;
    o.borrowShares = p.borrowShares;
    o.collateral = p.collateral;
    o.hasDebt = p.borrowShares > 0;
    o.totalBorrowShares = m.totalBorrowShares;
    o.lltv = e.params.lltv;

    // Simulate accrual to block.timestamp — MorphoBalancesLib.expectedMarketBalances inline. The IRM
    // reads the PRE-accrual market for utilization, so borrowRateView is passed the raw 'm'. Interest
    // is added only to totalBorrowAssets; totalBorrowShares is never touched by accrual. Zero-IRM /
    // zero-debt markets skip the block (rate 0), matching _accrueInterest.
    uint256 tba = m.totalBorrowAssets;
    {
      uint256 elapsed = block.timestamp - m.lastUpdate;
      if (elapsed != 0 && tba != 0 && e.params.irm != address(0)) {
        uint256 rate = IIrm(e.params.irm).borrowRateView(e.params, m);
        tba += _wMulDown(tba, _wTaylorCompounded(rate, elapsed));
      }
    }
    o.accruedTotalBorrowAssets = tba;

    uint256 price = IOracle(e.params.oracle).price();
    o.collateralPrice = price;

    // _isHealthy: borrowed rounds UP, maxBorrow rounds DOWN — both against the borrower. Liquidatable
    // iff !healthy (maxBorrow < borrowed).
    {
      uint256 borrowed = _toAssetsUp(p.borrowShares, tba, m.totalBorrowShares);
      uint256 maxBorrow = _wMulDown(_mulDivDown(p.collateral, price, ORACLE_PRICE_SCALE), e.params.lltv);
      o.healthy = maxBorrow >= borrowed;
    }
  }
}
`

/** What the lens reads for one (marketParams, borrower) pair. The lens re-derives the id from
 * `params` onchain and reads state at it, so a mismatched param set is rejected (valid=false). */
export type LensInput = { params: MarketParams; borrower: Address }

/** The decoded Solidity `LensOut` struct (uint64/128/256 → bigint per viem). */
type RawLensOut = {
  valid: boolean
  hasDebt: boolean
  healthy: boolean
  blockTimestamp: bigint
  borrowShares: bigint
  collateral: bigint
  accruedTotalBorrowAssets: bigint
  totalBorrowShares: bigint
  collateralPrice: bigint
  lltv: bigint
}

/**
 * The per-pair reading, with the market's `params` echoed back from the input. When `valid` is true
 * the onchain id-commitment check passed, so these params are the ones the market at that id was
 * created with — safe to feed straight into `quote`, `plan`, and `liquidate`.
 */
export type LensOut = RawLensOut & { params: MarketParams }

/**
 * Reads the liquidation lens for every pair in one deployless, chunked `eth_call` (no signer, no
 * cache — decisions need fresh state). The lens re-derives each market id from its params onchain.
 * Returns a map keyed by {@link lensKey} over `marketId(params)`. The `client` must use viem-dlc's
 * deployless transport (built in `client.ts`).
 */
export async function readBlueLiquidationLens(
  client: Client<Transport<BatchLensTransportType>>,
  morpho: Address,
  pairs: readonly LensInput[]
): Promise<Map<string, LensOut>> {
  // No `batch.gas`: the old polynomial fit does not carry over (the new model's `fixed` excludes the
  // copy of the chunk's own bytes, where `constant` folded in CREATE overhead), and a model viem-dlc
  // rejects as malformed is ignored silently in favour of packing by bytes. A chunk resizes from what
  // its own pages report, so stating nothing costs continuation round trips and never a result —
  // strictly better than a translated guess. Populate from the wide event's `fixed_gas` /
  // `item_gas_avg` / `item_gas_stddev` once real traffic has been observed.
  return readDeploylessBatchLens({
    client,
    parameters: {
      ...BlueLiquidationLens.with(morpho),
      functionName: 'computeOne',
      args: pairs
    },
    key: ({ params, borrower }) => lensKey(marketId(params), borrower),
    value: (input, out): LensOut => ({ ...out, params: input.params })
  })
}
